import streamlit as st
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np
import plotly.graph_objects as go
import cv2
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.optimizers import Adamax
from tensorflow.keras.metrics import Precision, Recall
import google.generativeai as genai # gemini model to generate explanations of the brain scans
import PIL.Image
import os
from dotenv import load_dotenv
import gdown
load_dotenv()

# Support both local .env and Streamlit Cloud secrets
try:
    api_key = st.secrets["GOOGLE_API_KEY"]
except:
    api_key = os.getenv("GOOGLE_API_KEY")

if api_key:
    genai.configure(api_key=api_key)

# Model download configuration
MODEL_FILES = {
    'cnn_model.h5': {
        'path': 'models/cnn_model.h5',
        'url': 'https://drive.google.com/uc?id=1-zvRYokb7WQF4QGZOpndgGKHWsEYUvfu'
    },
    'xception_model.weights.h5': {
        'path': 'models/xception_model.weights.h5',
        'url': 'https://drive.google.com/uc?id=1_O5VFfubbaoPd7HCwqziKt1UqnDx0zxK'
    }
}

def download_model_if_needed(model_name):
    """Download model from Google Drive if it doesn't exist locally"""
    model_info = MODEL_FILES[model_name]
    model_path = model_info['path']

    if not os.path.exists(model_path):
        st.info(f"Downloading {model_name} (first time only)... This may take a few minutes.")
        os.makedirs('models', exist_ok=True)
        gdown.download(model_info['url'], model_path, quiet=False)
        st.success(f"{model_name} downloaded successfully!")

    return model_path

# saliency maps is the directory where we store the saliency images

output_dir = 'saliency_maps'
os.makedirs(output_dir, exist_ok=True)


def generate_explanation(img_path, model_prediction, confidence):
    prompt = f"""You are an expert neurologist. You are tasked with explaining a saliency map of a brain tumor MRI scan.
    The saliency map was generated by a deep learning model that was trained to classify brain tumors
    as either glioma, meningioma, pituitary, or no tumor.

    The saliency map highlights the regions of the image that the machine learning model is focusing on to make the prediction.

    The deep learning model predicted the image to be of class '{model_prediction}' with a confidence of {confidence * 100}%.
    
    In your response:
    - Explain what regions of the brain the model is focusing on, based on the saliency map. Refer to the regions highlighted in light cyan, those are the regions where the model is focusing on.
    - Explain possible reasons why the model made the prediction it did.
    - Don't mention anything like 'The saliency map highlights the regions the model is focusing on, which are in light cyan' in your explanation.
    - Keep your explanation to 4 sentences max.
    """

    img = PIL.Image.open(img_path)

    model = genai.GenerativeModel(model_name="gemini-2.0-flash-exp")
    response = model.generate_content([prompt, img])

    return response.text



# saliency shows which pixels in the image were the most important to deduce the conclusion

def generate_saliency_map(model, img_array, class_index, img_size, img, uploaded_file):
    with tf.GradientTape() as tape:
        img_tensor = tf.convert_to_tensor(img_array)
        tape.watch(img_tensor)
        predictions = model(img_tensor)
        target_class = predictions[0, class_index]

    gradients = tape.gradient(target_class, img_tensor)
    gradients = tf.math.abs(gradients)
    gradients = tf.reduce_max(gradients, axis=-1)
    gradients = gradients.numpy().squeeze()

    # Resize gradients to match original image size
    gradients = cv2.resize(gradients, img_size)

    # Create a circular mask for the brain area
    center = (gradients.shape[0] // 2, gradients.shape[1] // 2)
    radius = min(center[0], center[1]) - 10
    x, y = np.ogrid[:gradients.shape[0], :gradients.shape[1]]
    mask = (x - center[0])**2 + (y - center[1])**2 <= radius**2

    # Apply mask to gradients
    gradients = gradients * mask

    # Normalize only the brain area
    brain_gradients = gradients[mask]
    if brain_gradients.max() > brain_gradients.min():
        brain_gradients = (brain_gradients - brain_gradients.min()) / (brain_gradients.max() - brain_gradients.min())
        gradients[mask] = brain_gradients

    # Apply a higher threshold
    threshold = np.percentile(gradients[mask], 80)
    gradients[gradients < threshold] = 0

    # Apply more aggressive smoothing
    gradients = cv2.GaussianBlur(gradients, (11, 11), 0)

    # Create a heatmap overlay with enhanced contrast
    heatmap = cv2.applyColorMap(np.uint8(255 * gradients), cv2.COLORMAP_JET)
    heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)

    # Resize heatmap to match original image size
    heatmap = cv2.resize(heatmap, img_size)

    # Superimpose the heatmap on the original image with increased opacity
    original_img = image.img_to_array(img)
    superimposed_img = heatmap * 0.7 + original_img * 0.3
    superimposed_img = superimposed_img.astype(np.uint8)

    img_path = os.path.join(output_dir, uploaded_file.name)
    with open(img_path, "wb") as f:
        f.write(uploaded_file.getbuffer())

    saliency_map_path = f'saliency_maps/{uploaded_file.name}'

    # Save the saliency map
    cv2.imwrite(saliency_map_path, cv2.cvtColor(superimposed_img, cv2.COLOR_RGB2BGR))

    return superimposed_img


# use the load_xcception_model part of its package
# for cnn we use the load_model from streamlit or tensorflow

def load_xception_model(model_path):
    img_shape = (299, 299, 3)
    base_model = tf.keras.applications.Xception(
        include_top=False,
        weights="imagenet",
        input_shape=img_shape,
        pooling="max"
    )

    model = Sequential([
        base_model,
        Flatten(),
        Dropout(rate=0.3),
        Dense(128, activation='relu'),
        Dropout(rate=0.25),
        Dense(4, activation='softmax')
    ])

    model.build((None,) + img_shape)

    # Compile the model
    model.compile(
        Adamax(learning_rate=0.001),
        loss='categorical_crossentropy',
        metrics=['accuracy', Precision(), Recall()]
    )

    model.load_weights(model_path)
    return model


st.title("Brain Tumor Classification")
st.write("Upload an image of a brain MRI scan to classify.")

# Sample images section
st.write("### Try with sample images:")
col1, col2, col3, col4 = st.columns(4)

sample_images = {
    'Glioma': 'sample_data/Glioma.png',
    'Meningioma': 'sample_data/Meningioma.png',
    'No Tumor': 'sample_data/NoTumor.png',
    'Pituitary': 'sample_data/Pituitary.png'
}

# Initialize session state for selected sample
if 'selected_sample' not in st.session_state:
    st.session_state.selected_sample = None

with col1:
    st.image(sample_images['Glioma'], caption='Glioma', use_container_width=True)
    if st.button('Use Glioma Sample'):
        st.session_state.selected_sample = sample_images['Glioma']

with col2:
    st.image(sample_images['Meningioma'], caption='Meningioma', use_container_width=True)
    if st.button('Use Meningioma Sample'):
        st.session_state.selected_sample = sample_images['Meningioma']

with col3:
    st.image(sample_images['No Tumor'], caption='No Tumor', use_container_width=True)
    if st.button('Use No Tumor Sample'):
        st.session_state.selected_sample = sample_images['No Tumor']

with col4:
    st.image(sample_images['Pituitary'], caption='Pituitary', use_container_width=True)
    if st.button('Use Pituitary Sample'):
        st.session_state.selected_sample = sample_images['Pituitary']

st.write("### Or upload your own image:")
uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

# Use sample if selected, otherwise use uploaded file
if st.session_state.selected_sample is not None:
    uploaded_file = st.session_state.selected_sample
    st.info(f"Using sample image: {os.path.basename(uploaded_file)}")
    # Reset after use
    if st.button("Clear sample selection"):
        st.session_state.selected_sample = None
        st.rerun()

# the user has uploaded an image for scanning we want to give them the choice to choose between
# the transfer learning model using xception
# the custom onvolutional neural network model

if uploaded_file is not None:
    selected_model = st.radio(
        "Select Model",
        ("Transfer Learning - Xception" ,"Custom CNN")
    )

    if selected_model == "Transfer Learning - Xception":
        model_path = download_model_if_needed('xception_model.weights.h5')
        model = load_xception_model(model_path)
        img_size = (299,299)
    else:
        model_path = download_model_if_needed('cnn_model.h5')
        model = load_model(model_path)
        img_size = (224,224)

    labels = ['Glioma', 'Meningioma', 'No tumor', 'Pituitary']
    img = image.load_img(uploaded_file, target_size=img_size)
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array /= 255.0

    prediction = model.predict(img_array)

    # Get the class with the highest probability
    class_index = np.argmax(prediction[0])
    result = labels[class_index]

    st.write(f"Predicted Class: {result}")
    st.write("Predictions:")
    for label, prob in zip(labels, prediction[0]):
        st.write(f"{label}: {prob:.4f}")

    saliency_map = generate_saliency_map(model, img_array, class_index, img_size, img, uploaded_file)

    col1, col2 = st.columns(2)
    with col1:
        st.image(uploaded_file, caption='Uploaded Image', use_container_width=True)
    with col2:
        st.image(saliency_map, caption='Saliency Map', use_container_width=True)

    saliency_map_path = f'saliency_maps/{uploaded_file.name}'
    explanation = generate_explanation(saliency_map_path, result, prediction[0][class_index])

    st.write("## Explanation")
    st.write(explanation)

